### ISSUE TITLE
qdarktheme

### ISSUE THREAD

**Issue by cerinawithasea** [spookyahell/pyOneFichierClient#11]
_after install i tried to run and i get_
`python 1fichier-dl.py
Traceback (most recent call last):
  File "/Users/cerinawithasea/Downloads/1fichier-dl-main/1fichier-dl.py", line 5, in <module>
    from core.gui import gui
  File "/Users/cerinawithasea/Downloads/1fichier-dl-main/core/gui/gui.py", line 7, in <module>
    import qdarktheme
ModuleNotFoundError: No module named 'qdarktheme'`
_my chatbot tried a few things then said_
`It looks like `qdarktheme` is not available for installation via pip, which could indicate a typo in the module name, a private package not hosted on PyPI, or the need for a different method of installation. Here are a few steps you can try:

1. Double-check the spelling of the module name in your script, `1fichier-dl.py`, and confirm it matches the intended package you're trying to use.
2. If it is supposed to be a public package, search for `qdarktheme` or a similar name on PyPI to confirm its availability and correct spelling.
3. If `qdarktheme` is intended to be a third-party or proprietary library, make sure you have access, and check any documentation provided to obtain it.

_If it's none of these, you may need to contact the developer of the script or consult its documentation for further guidance.`
she has never quit and told me to contact the dev, so here i am. I absolutely am not comfortable messing with the script all willy nilly
I don't know if it matters but im on a m1 macbook air_
I also tried to do it in a venv and the exact same thing happened

**Comment by spookyahell** [comment]
May I ask you to...?

- [ ]  double-check if you think this is the right place to report this error
- [ ] hopefully quickly come to the realization that it is not
